/*
Name             : Calc
Version          : 0.01
Author           : GOLD Parser Builder and Nick Sabalausky
About            : Basic Calculator Grammar
Case Sensitive   : 
Start Symbol     : 

Character Set     : Unicode
Character Mapping : Windows-1252
Generated By      : GOLD Parser Builder 5.2.0.
Generated Date    : 2021-12-15 17:24

Output File      : TestCalc.js 
Output File Base : TestCalc 


This file was generated by the Gold Parser.
The template is Javascript OO Engine

*/

const Calc = require('./Calc');
const input = '2+2*2';
const DEBUG_LEVEL = 0;
const TRIM_REDUCTIONS = 1;
const parser = new Calc(input,TRIM_REDUCTIONS,DEBUG_LEVEL);

parser.parse();
console.log(parser.output.join(''));
console.log(parser.result);
