
/*
Name             : Calc
Version          : 0.01
Author           : GOLD Parser Builder and Nick Sabalausky
About            : Basic Calculator Grammar
Case Sensitive   : 
Start Symbol     : 

Character Set     : Unicode
Character Mapping : Windows-1252
Generated By      : GOLD Parser Builder 5.2.0.
Generated Date    : 2021-12-02 19:11

Output File      :  
Output File Base :  


This file was generated by the Gold Parser.
The template is Javascript OO Engine

*/

const TestCalc = require('./TestCalc');
const input = '';
const parser = new TestCalc(input,0,0);
p.debug = 0;
p.run();
