/*
Name             : Calc
Version          : 0.01
Author           : GOLD Parser Builder and Nick Sabalausky
About            : Basic Calculator Grammar
Case Sensitive   : 
Start Symbol     : 

Character Set     : Unicode
Character Mapping : Windows-1252
Generated By      : GOLD Parser Builder 5.2.0.
Generated Date    : 2021-12-15 15:01

Output File      : TestCalc.js 
Output File Base : TestCalc 


This file was generated by the Gold Parser.
The template is Javascript OO Engine

*/


const Calc = require('./Calc');
const input = '';
const parser = new Calc(input,1,0);

parser.debug = 0;
parser.parse();
